### ISSUE TITLE
Pageview always fullscreen

### ISSUE THREAD

**Issue by LeonHermann322** [hpi-dhc/comprehension-measurement#20]

**Comment by LeonHermann322** [comment]
PageView is always fullscreen because it's wrapped in a Flexible. However if we remove the Flexible we get an error. 
The Problem: PageView doesn't know the size of its children. Therefore it tries to take as much space as possible if it isn't constrained by a fixed size.

**Comment by DevSchmidtchen** [comment]
Closed by https://github.com/hpi-dhc/comprehension-measurement/commit/01577e8e4887cb3a2deaec9898cd3b0b38104368
